In [1]:
import sys
from pathlib import Path
root = Path.cwd()
while not (root / "Models").is_dir():
    root = root.parent
sys.path.insert(0, str(root))

from config import *

from Models.Papers.Planck2018 import Planck2018

In [5]:
importlib.reload(Planck2018)

Planck2018.Table1().df

Parameter,Ob0h2,Oc0h2,100thetaMC,tau,ln1e10As,ns,Om0h2,H0,Om0,Age_Gyr,sigma8,S8,zre,100thetastar,rdrag_Mpc
Parameter,,,,,,,,,,,,,,,
Plik best fit,0.022383,0.12011,1.040909,0.0543,3.0448,0.96605,0.14314,67.32,0.3158,13.7971,0.8120,0.8331,7.68,1.041085,147.049
Plik [1],0.022370,0.12000,1.040920,0.0544,3.0440,0.96490,0.14300,67.36,0.3153,13.7970,0.8111,0.8320,7.67,1.041100,147.090
CamSpec [2],0.022290,0.11970,1.040870,0.0536,3.0410,0.96560,0.14260,67.39,0.3142,13.8050,0.8091,0.8280,7.61,1.041060,147.260
([2]-[1])/σ1,-0.500000,-0.30000,-0.200000,-0.1000,-0.3000,0.20000,-0.30000,0.10,-0.2000,0.4000,-0.3000,-0.3000,-0.10,-0.100000,0.600
Combined,0.022330,0.11980,1.040890,0.0540,3.0430,0.96520,0.14280,67.37,0.3147,13.8010,0.8101,0.8300,7.64,1.041080,147.180

In [6]:
importlib.reload(Planck2018)

Planck2018.Table2().df

Parameter,Ob0h2,Oc0h2,100thetaMC,tau,ln1e10As,ns,H0,Ol0,Om0,Om0h2,...,100thetastar,zdrag,rdrag_Mpc,kD_invMpc,zeq,keq_invMpc,100thetaseq,f2000_143,f2000_143x217,f2000_217
Parameter,,,,,,,,,,,,,,,,,,,,,
TT+lowE,0.02212,0.12060,1.04077,0.0522,3.040,0.9626,66.88,0.6790,0.3210,0.1434,...,1.04097,1059.39,147.21,0.14054,3411.0,0.010410,0.4483,31.2,33.6,108.2
TE+lowE,0.02249,0.11770,1.04139,0.0496,3.018,0.9670,68.44,0.6990,0.3010,0.1408,...,1.04156,1060.03,147.59,0.14043,3349.0,0.010220,0.4547,NaN,NaN,NaN
EE+lowE,0.02400,0.11580,1.03999,0.0527,3.052,0.9800,69.90,0.7110,0.2890,0.1404,...,1.04001,1063.20,146.46,0.14260,3340.0,0.010190,0.4562,NaN,NaN,NaN
"TT,TE,EE+lowE",0.02236,0.12020,1.04090,0.0544,3.045,0.9649,67.27,0.6834,0.3166,0.1432,...,1.04109,1059.93,147.05,0.14090,3407.0,0.010398,0.4490,29.5,32.2,107.0
"TT,TE,EE+lowE+lensing",0.02237,0.12000,1.04092,0.0544,3.044,0.9649,67.36,0.6847,0.3153,0.1430,...,1.04110,1059.94,147.09,0.14087,3402.0,0.010384,0.4494,29.6,32.3,107.1
"TT,TE,EE+lowE+lensing+BAO",0.02242,0.11933,1.04101,0.0561,3.047,0.9665,67.66,0.6889,0.3111,0.1424,...,1.04119,1060.01,147.21,0.14078,3387.0,0.010339,0.4509,29.4,32.1,106.9

In [8]:
importlib.reload(Planck2018)

print(Planck2018.Cosmology().H0)
print(Planck2018.Cosmology(H0=70).H0)

67.66
70